************* Module dpl
dpl.py:51:0: C0301: Line too long (136/100) (line-too-long)
dpl.py:79:0: C0301: Line too long (122/100) (line-too-long)
dpl.py:93:0: C0301: Line too long (101/100) (line-too-long)
dpl.py:95:0: C0301: Line too long (103/100) (line-too-long)
dpl.py:110:0: C0301: Line too long (105/100) (line-too-long)
dpl.py:111:0: C0301: Line too long (105/100) (line-too-long)
dpl.py:134:0: C0301: Line too long (240/100) (line-too-long)
dpl.py:139:0: C0301: Line too long (118/100) (line-too-long)
dpl.py:169:0: C0301: Line too long (199/100) (line-too-long)
dpl.py:176:0: C0301: Line too long (199/100) (line-too-long)
dpl.py:187:0: C0301: Line too long (156/100) (line-too-long)
dpl.py:190:0: C0301: Line too long (119/100) (line-too-long)
dpl.py:232:0: C0301: Line too long (146/100) (line-too-long)
dpl.py:245:0: C0301: Line too long (121/100) (line-too-long)
dpl.py:345:26: C0303: Trailing whitespace (trailing-whitespace)
dpl.py:149:0: R1707: Disallow trailing comma tuple (trailing-comma-tuple)
dpl.py:1:0: C0114: Missing module docstring (missing-module-docstring)
dpl.py:14:0: C0413: Import "import subprocess" should be placed at the top of the module (wrong-import-position)
dpl.py:15:0: C0413: Import "import shutil" should be placed at the top of the module (wrong-import-position)
dpl.py:16:0: C0413: Import "import time" should be placed at the top of the module (wrong-import-position)
dpl.py:17:0: C0413: Import "import pstats" should be placed at the top of the module (wrong-import-position)
dpl.py:18:0: R0402: Use 'from lib.core import info' instead (consider-using-from-import)
dpl.py:18:0: C0413: Import "import lib.core.info as info" should be placed at the top of the module (wrong-import-position)
dpl.py:19:0: R0402: Use 'from lib.core import utils' instead (consider-using-from-import)
dpl.py:19:0: C0413: Import "import lib.core.utils as utils" should be placed at the top of the module (wrong-import-position)
dpl.py:20:0: R0402: Use 'from lib.core import error' instead (consider-using-from-import)
dpl.py:20:0: C0413: Import "import lib.core.error as error" should be placed at the top of the module (wrong-import-position)
dpl.py:21:0: C0413: Import "import lib.core.cli_arguments as cli_args" should be placed at the top of the module (wrong-import-position)
dpl.py:22:0: C0413: Import "import lib.core.extension_support as ext_s" should be placed at the top of the module (wrong-import-position)
dpl.py:23:0: C0413: Import "from dfpm import dfpm" should be placed at the top of the module (wrong-import-position)
dpl.py:24:0: C0413: Import "from documenter import docs" should be placed at the top of the module (wrong-import-position)
dpl.py:25:0: C0413: Import "import cProfile" should be placed at the top of the module (wrong-import-position)
dpl.py:29:7: W0718: Catching too general exception Exception (broad-exception-caught)
dpl.py:28:4: R0402: Use 'from lib.core import parser' instead (consider-using-from-import)
dpl.py:31:0: R0402: Use 'from lib.core import varproc' instead (consider-using-from-import)
dpl.py:31:0: C0413: Import "import lib.core.varproc as varproc" should be placed at the top of the module (wrong-import-position)
dpl.py:32:0: W0404: Reimport 'lib.core.utils' (imported line 19) (reimported)
dpl.py:32:0: R0402: Use 'from lib.core import utils' instead (consider-using-from-import)
dpl.py:32:0: C0413: Import "import lib.core.utils as utils" should be placed at the top of the module (wrong-import-position)
dpl.py:36:4: C0103: Constant name "has_dill" doesn't conform to UPPER_CASE naming style (invalid-name)
dpl.py:39:4: C0103: Constant name "has_dill" doesn't conform to UPPER_CASE naming style (invalid-name)
dpl.py:43:0: C0116: Missing function or method docstring (missing-function-docstring)
dpl.py:47:17: W0621: Redefining name 'i' from outer scope (line 348) (redefined-outer-name)
dpl.py:53:0: C0116: Missing function or method docstring (missing-function-docstring)
dpl.py:69:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:71:0: C0116: Missing function or method docstring (missing-function-docstring)
dpl.py:71:0: R0914: Too many local variables (32/15) (too-many-locals)
dpl.py:141:16: W0621: Redefining name 'i' from outer scope (line 348) (redefined-outer-name)
dpl.py:85:16: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:87:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:92:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:99:16: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:101:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:112:19: W0718: Catching too general exception Exception (broad-exception-caught)
dpl.py:115:16: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:119:16: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:125:19: W0718: Catching too general exception Exception (broad-exception-caught)
dpl.py:122:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:128:16: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:136:16: C0415: Import outside toplevel (lib.core.build) (import-outside-toplevel)
dpl.py:154:16: W0702: No exception type(s) specified (bare-except)
dpl.py:161:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:169:109: R1714: Consider merging these comparisons with 'in' by using 'temp in (sys.platform, 'any')'. Use a set instead if elements are hashable. (consider-using-in)
dpl.py:176:109: R1714: Consider merging these comparisons with 'in' by using 'temp in (sys.platform, 'any')'. Use a set instead if elements are hashable. (consider-using-in)
dpl.py:184:25: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:189:31: W0718: Catching too general exception Exception (broad-exception-caught)
dpl.py:187:31: W1510: 'subprocess.run' used without explicitly defining the value for 'check'. (subprocess-run-check)
dpl.py:216:29: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
dpl.py:216:29: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:229:12: C0103: Variable name "PROMPT_CTL" doesn't conform to snake_case naming style (invalid-name)
dpl.py:233:12: C0103: Variable name "START_FILE" doesn't conform to snake_case naming style (invalid-name)
dpl.py:238:16: W0702: No exception type(s) specified (bare-except)
dpl.py:236:25: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:244:20: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:250:28: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:265:27: W0718: Catching too general exception BaseException (broad-exception-caught)
dpl.py:279:24: W0702: No exception type(s) specified (bare-except)
dpl.py:277:33: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
dpl.py:285:23: W0718: Catching too general exception Exception (broad-exception-caught)
dpl.py:332:12: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
dpl.py:71:0: R0912: Too many branches (62/12) (too-many-branches)
dpl.py:71:0: R0915: Too many statements (191/50) (too-many-statements)
dpl.py:346:8: C0103: Constant name "default" doesn't conform to UPPER_CASE naming style (invalid-name)
dpl.py:347:8: C0103: Constant name "order_by" doesn't conform to UPPER_CASE naming style (invalid-name)
dpl.py:25:0: C0411: standard import "cProfile" should be placed before first party imports "lib.core.info", "lib.core.utils", "lib.core.error" (...) "lib.core.extension_support", "dfpm.dfpm", "documenter.docs"  (wrong-import-order)
dpl.py:28:4: C0412: Imports from package lib are not grouped (ungrouped-imports)

------------------------------------------------------------------
Your code has been rated at 6.81/10 (previous run: 6.81/10, +0.00)

